---
name: Application Build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [
            { name: 'linux',   image: 'ubuntu-latest' },
            { name: 'windows', image: 'windows-latest' },
            { name: 'macos',   image: 'macos-latest' }
          ]
        arch: [ 'x64', 'arm64' ]
      fail-fast: false
          

    runs-on: ${{ matrix.os.image }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Setup Node (v18)
        uses: actions/setup-node@v3
        with:
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache: 'yarn'
          node-version: 18

      - name: Install dependencies
        run: yarn --immutable

      - name: Build (${{ matrix.arch }})
        # if: matrix.os.image == 'macos-latest'
        run: yarn make --arch ${{ matrix.arch }}

      - name: Upload artifacts (${{ matrix.arch }})
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.os.name }}-${{ matrix.arch }}
          path: |
            out/make/squirrel.windows/${{ matrix.arch }}/*.exe
            out/make/deb/${{ matrix.arch }}/*.deb
            out/make/rpm/${{ matrix.arch }}/*.rpm
            out/make/zip/darwin/${{ matrix.arch }}/*.zip
